name: Unit Tests
description: Run unit tests in different python environments
inputs:
  python-version:
    required: true
    description: "Python version to run the tests"
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Dev Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt
      shell: bash

    - name: Install Tox
      run: pip install tox
      shell: bash

    - name: Run Tox lint commands
      # Run tox using the version of Python in `PATH`
      run: tox -e lint
      shell: bash

    - name: Run Pytest through Tox
      # Run tox using the version of Python in `PATH`
      run: tox -e unit
      shell: bash

    - name: Run pip-audit command through GHA
      # Check dependencies for security vulnerabilities
      uses: pypa/gh-action-pip-audit@v1.0.8
      with:
        inputs: requirements.txt
