name: Unit Tests
description: Run unit tests in different python environments
inputs:
  python-version:
    required: true
    description: "Python version to run the tests"
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Cython
      run: |
        python -m pip install --upgrade pip
        pip install Cython numpy wheel
      shell: bash

    - name: Install Tox
      run: pip install tox
      shell: bash

    - name: Run Tox lint commands
      # Run tox using the version of Python in `PATH`
      run: tox -e lint
      shell: bash

    - name: Run Pytest through Tox
      # Run tox using the version of Python in `PATH`
      run: tox -e unit
      shell: bash