FROM pytorch/pytorch:1.13.0-cuda11.6-cudnn8-runtime
#FROM bitnami/pytorch:latest

USER root
RUN groupadd -r dockuser && useradd -r -g dockuser dockuser
WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY src .

ENV PYTHONPATH "${PYTHONPATH}:/app"

RUN chown dockuser:dockuser /app
#USER dockuser

CMD ["python", "casp/ml/training/pca/train.py"]