# tox (https://tox.readthedocs.io/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
envlist = lint,py310,py311
skip_missing_interpreters = true
isolated_build = true

[flake8]
max-line-length = 120
select = C,E,F,W,B,B950
ignore = E203, E501, W503
exclude =
    .git,
    __pycache__,
    .tox,
    .eggs,
    *.egg,
    build,
    dist,
    .venv,
    venv

[testenv]
deps =
    pytest>=8.1.1
    pytest-asyncio>=0.23.6
    pytest-cov>=5.0.0
    pytest-dependency>=0.6.0
    parameterized>=0.9.0
    mockito>=1.5.0
    coverage>=4.5
    click>=8.0.0
    requests>=2.31.0
    termcolor>=2.4.0
    pygments>=2.17.2
    scikit-learn>=1.4.0
    torch>=2.2.2
    mock-alchemy==0.2.4
allowlist_externals = poetry
commands_pre =
    poetry install --with dev,test --no-root
commands =
    pytest --cov=cellarium.cas_backend tests/unit tests/integration \
        --cov-report term-missing \
        --cov-report html \
        --cov-report xml \
        {posargs}
setenv =
    ENVIRONMENT = test
    PYTHONPATH = {toxinidir}
    TEST_DB_FILE_PATH = {envtmpdir}/test_db.sqlite

[testenv:unit]
deps = {[testenv]deps}
    numpy
    cython
allowlist_externals = poetry
commands_pre =
    poetry install --with dev,test --no-root
commands =
    pytest --cov=cellarium.cas_backend tests/unit \
        --cov-report term-missing \
        --cov-report html \
        --cov-report xml \
        {posargs}

[testenv:integration]
deps = {[testenv]deps}
allowlist_externals = poetry
commands_pre =
    poetry install --with dev,test --no-root
commands =
    pytest tests/integration {posargs}

[testenv:lint]
deps =
    numpy
    cython
    pylint
    black
    flake8
    isort
allowlist_externals = poetry
commands_pre =
    poetry install --with dev --no-root
commands =
    black --line-length 120 --check cellarium tests
    isort --check-only --diff --line-length 120 --profile black tests cellarium
    flake8 cellarium tests
    pylint --exit-zero --max-line-length 120 cellarium tests

[testenv:format]
# install black in a virtual environment and invoke it on the current folder
deps =
    black
    isort
skip_install = true
commands =
    black --line-length 120 cellarium tests
    isort --line-length 120 --profile black tests cellarium

[gh-actions]
python =
    3.10: py310
    3.11: py311
