# tox (https://tox.readthedocs.io/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.
[tox]
envlist = lint,py310,py311,unit,integration
skip_missing_interpreters = true

[testenv]
allowlist_externals = poetry
commands_pre =
    poetry install --with test --no-interaction --no-root
commands =
    pytest --cov=cellarium.cas_backend tests/unit tests/integration --cov-report=term-missing {posargs}
setenv =
    ENVIRONMENT = test
    PYTHONPATH = {toxinidir}
    TEST_DB_FILE_PATH = {envtmpdir}/test_db.sqlite

[testenv:unit]
allowlist_externals = poetry
commands_pre =
    poetry install --with test --no-interaction --no-root
commands =
    pytest tests/unit {posargs}

[testenv:integration]
allowlist_externals = poetry
commands_pre =
    poetry install --with test --no-interaction --no-root
commands =
    pytest tests/integration {posargs}

[testenv:lint]
allowlist_externals = poetry
commands_pre =
    poetry install --with dev --no-interaction --no-root
commands =
    black --line-length 120 --check cellarium tests
    isort --check-only --diff --line-length 120 --profile black tests cellarium
    flake8 cellarium tests

[testenv:format]
allowlist_externals = poetry
commands_pre =
    poetry install --with dev --no-interaction --no-root
commands =
    black --line-length 120 cellarium tests
    isort --line-length 120 --profile black tests cellarium