benchmark_cas:
  machine_specs:
    benchmark_cas:
      display_name: Benchmark CAS
      replica_count: 1
      machine_type: n1-highmem-16
      accelerator_type: null
      accelerator_count: null
      base_image: us-central1-docker.pkg.dev/dsp-cell-annotation-service/cas-services-cicd/cas-pytorch-pipeline-dev:1.4.6-alpha.1
      env:
        - name: WANDB_API_KEY
          value: 2bc373264f98a15fac0e869d98f7b207d575937d

  pipeline_configs:
    - benchmark_cas__model_name: jrb_pca_512_all_genes_log1p_zscore
      benchmarking_data_paths:
        - gs://cellarium-file-system/dev/ingest_2024/data/218acb0f-9f2f-4f76-b90b-15a4b7c7f629#cece7dd6-cad7-450d-8b1c-841d49552cea__census_dataset.h5ad
        - gs://cellarium-file-system/dev/ingest_2024/data/9df60c57-fdf3-4e93-828e-fe9303f20438#47de6fa9-411b-429a-a04f-318930848a3c__census_dataset.h5ad
      cas_api_token: 521da69c-6977-4913-a32b-b1ded563f170.e07f59d5-7043-4a8c-84b0-17d09f076ca2
      cas_api_url: https://benchmarking-cas-api-vi7nxpvk7a-uc.a.run.app
      cell_ontology_resource_path: gs://cellarium-file-system/dev/benchmarking_june_2024/metadata/co_resource.pickle
      cl_labels_to_names_map_path: gs://cellarium-file-system/dev/benchmarking_june_2024/metadata/cl_labels_to_names_map.pickle
      deployed_index_id: deployed_jrb_pca_512_all_genes_log1p_zscore_index
      index_display_name: Some Name
      index_endpoint_id: 2348891088464379904
      index_id: 5306353066809753600
      index_name: jrb_pca_512_all_genes_log1p_zscore_index
      index_region: us-central1
      metrics_metadata_path: gs://cellarium-file-system/dev/benchmarking_june_2024/metrics/
      project_id: project_id
      wandb_project: benchmarking_runs