calculate_metrics:
  machine_specs:
    calculate_metrics:
      display_name: Calculate Metrics
      replica_count: 1
      machine_type: e2-standard-32
      accelerator_type: null
      accelerator_count: null
      base_image: us-central1-docker.pkg.dev/dsp-cell-annotation-service/cas-services-cicd/cas-pytorch-pipeline-dev:1.4.6-alpha.1
      env:
        - name: WANDB_API_KEY
          value: 2bc373264f98a15fac0e869d98f7b207d575937d

  pipeline_configs:
    - batch_size: 5000
      calculate_metrics__model_name: jrb_pca_64_hv10000genes_zscore
      cas_result_paths: gs://cellarium-file-system/dev/benchmarking_june_2024/metadata/cas_outputs_names/jrb_pca_64_hv10000genes_zscore_cas_outputs.txt
      cell_ontology_resource_path: gs://cellarium-file-system/dev/benchmarking_june_2024/metadata/co_resource.pickle
      cl_labels_to_names_map_path: gs://cellarium-file-system/dev/benchmarking_june_2024/metadata/cl_labels_to_names_map.pickle
      dataset_paths: gs://cellarium-file-system/dev/benchmarking_june_2024/metadata/dataset_paths.txt
      metrics_metadata_path: gs://cellarium-file-system/dev/benchmarking_june_2024/metrics
      num_hops: 4
      wandb_project: benchmarking_runs
