generate_cas_outputs:
  machine_specs:
    generate_cas_outputs:
      display_name: Generate CAS Outputs
      replica_count: 1
      machine_type: e2-highmem-16
      accelerator_type: null
      accelerator_count: null
      base_image: us-central1-docker.pkg.dev/dsp-cell-annotation-service/cas-services-cicd/cas-pytorch-pipeline-dev:1.4.6-alpha.1
      env:
        - name: WANDB_API_KEY
          value: 2bc373264f98a15fac0e869d98f7b207d575937d

  pipeline_configs:
    - cas_api_token: 521da69c-6977-4913-a32b-b1ded563f170.e07f59d5-7043-4a8c-84b0-17d09f076ca2
      cas_api_url: https://benchmarking-cas-api-vi7nxpvk7a-uc.a.run.app
      cas_results_output_path: gs://cellarium-file-system/dev/benchmarking_june_2024/cas_outputs
      dataset_paths: gs://cellarium-file-system/dev/benchmarking_june_2024/metadata/dataset_paths_test_large_new.txt
      deployed_index_id: deployed_jrb_pca_64_hvcutoffsgenes_zscore_index
      generate_cas_outputs__model_name: jrb_pca_64_hvcutoffsgenes_zscore
      index_display_name: deployed_jrb_pca_64_hvcutoffsgenes_zscore_index
      index_endpoint_id: 3388382575503343616
      index_id: 5237110222538932224
      index_name: jrb_pca_64_hvcutoffsgenes_zscore_index
      index_region: us-central1
      metrics_metadata_path: gs://cellarium-file-system/dev/benchmarking_june_2024/metrics/
      project_id: dsp-cell-annotation-service