logistic_regression:
  machine_specs:
    logistic_regression_train:
      display_name: Logistic Regression Training
      replica_count: 1
      machine_type: n1-highmem-16
      accelerator_type: NVIDIA_TESLA_T4
      accelerator_count: 2
      base_image: us-central1-docker.pkg.dev/dsp-cell-annotation-service/cas-services-cicd/cas-pytorch-cuda-pipeline-dev:1.4.5-alpha.1

  pipeline_configs:
    - curriculum_name: human_10x_only_2024_05_16_ingest
      shard_size: 10000
      extract_start: 0
      extract_end: 3737
  #    extract_end: 2930
  #    last_shard_size: 6596
      last_shard_size: 9002
      use_log_1p: true
      normalize_total_eps: 1e-6
      normalize_total_target_count: 10000
      W_prior_scale: 1
      lr: 1e-3
      max_epochs: 20
      scheduler_num_training_steps: 22814
      batch_size: 2048
      use_filter: true
      filter_file_path: gs://cellarium-file-system/curriculum/human_10x_only_2024_05_16_ingest/models/shared_meta/features-mean-gt-0-01.csv
      logistic_regression_train__model_name: logistic_regression_W_prior_1_scheduler_batch_2048_2_gpu_epochs_20_log1p_divide_by_scale_filter_features_v1
      logistic_regression_train__mean_var_std_model_name: mean_var_std_log1p_v1
      logistic_regression_train__tdigest_model_name: tdigest_log1p_v1
      logistic_regression_train__use_zscore: false
      logistic_regression_train__use_divide_by_scale: true

    - curriculum_name: human_10x_only_2024_05_16_ingest
      shard_size: 10000
      extract_start: 0
      extract_end: 3737
      last_shard_size: 9002
      use_log_1p: true
      normalize_total_eps: 1e-6
      normalize_total_target_count: 10000
      W_prior_scale: 1e-4
      lr: 1e-3
      max_epochs: 20
      scheduler_num_training_steps: 22814
      batch_size: 2048
      use_filter: true
      filter_file_path: gs://cellarium-file-system/curriculum/human_10x_only_2024_05_16_ingest/models/shared_meta/features-mean-gt-0-01.csv
      logistic_regression_train__model_name: logistic_regression_W_prior_1e-4_scheduler_batch_2048_2_gpu_epochs_20_log1p_divide_by_scale_filter_features_v1
      logistic_regression_train__mean_var_std_model_name: mean_var_std_log1p_v1
      logistic_regression_train__tdigest_model_name: tdigest_log1p_v1
      logistic_regression_train__use_zscore: false
      logistic_regression_train__use_divide_by_scale: true

    - curriculum_name: human_10x_only_2024_05_16_ingest
      shard_size: 10000
      extract_start: 0
      extract_end: 3737
      last_shard_size: 9002
      use_log_1p: true
      normalize_total_eps: 1e-6
      normalize_total_target_count: 10000
      W_prior_scale: 1
      lr: 1e-3
      max_epochs: 20
      scheduler_num_training_steps: 22814
      batch_size: 2048
      use_filter: true
      filter_file_path: gs://cellarium-file-system/curriculum/human_10x_only_2024_05_16_ingest/models/shared_meta/tdigest_log1p_v1-non-nan-features.csv
      logistic_regression_train__model_name: logistic_regression_W_prior_1_scheduler_batch_2048_2_gpu_epochs_20_log1p_divide_by_scale_v1
      logistic_regression_train__mean_var_std_model_name: mean_var_std_log1p_v1
      logistic_regression_train__tdigest_model_name: tdigest_log1p_v1
      logistic_regression_train__use_zscore: false
      logistic_regression_train__use_divide_by_scale: true

    - curriculum_name: human_10x_only_2024_05_16_ingest
      shard_size: 10000
      extract_start: 0
      extract_end: 3737
      last_shard_size: 9002
      use_log_1p: true
      normalize_total_eps: 1e-6
      normalize_total_target_count: 10000
      W_prior_scale: 1e-4
      lr: 1e-3
      max_epochs: 20
      scheduler_num_training_steps: 22814
      batch_size: 2048
      use_filter: true
      filter_file_path: gs://cellarium-file-system/curriculum/human_10x_only_2024_05_16_ingest/models/shared_meta/tdigest_log1p_v1-non-nan-features.csv
      logistic_regression_train__model_name: logistic_regression_W_prior_1e-4_scheduler_batch_2048_2_gpu_epochs_20_log1p_divide_by_scale_v1
      logistic_regression_train__mean_var_std_model_name: mean_var_std_log1p_v1
      logistic_regression_train__tdigest_model_name: tdigest_log1p_v1
      logistic_regression_train__use_zscore: false
      logistic_regression_train__use_divide_by_scale: true