name: Update Docker Images
description: Update docker images in GCP Artifact Registry
inputs:
  docker-registry-name:
    required: true
    description: GCP Docker registry name
  gcp-provider-id:
    required: true
    description: CAS GCP provider ID
  gcp-service-account-email:
    required: true
    description: CAS Deployer service account email
  image-tag:
    required: true
    description: Current workflow tag
  env-secrets-b64:
    required: true
    description: Secret environment variables (db hosts, password salt, etc)
  docker-file-path:
    required: true
    description: Path to the Dockerfile
  image-name:
    required: true
    description: Image name in the artifact registry

runs:
  using: "composite"
  steps:
    - id: checkout
      name: Checkout
      uses: actions/checkout@v2

    - name: Authenticate with Google Cloud
      id: google-login
      uses: google-github-actions/auth@v0
      with:
        token_format: access_token
        workload_identity_provider: ${{ inputs.gcp-provider-id }}
        service_account: ${{ inputs.gcp-service-account-email }}
        access_token_lifetime: 1500s

    - name: Login to Artifact Registry
      id: docker-google-login
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.docker-registry-name }}
        username: oauth2accesstoken
        password: ${{ steps.google-login.outputs.access_token }}

    - name: Update Docker image in Google Artifact Registry
      uses: docker/build-push-action@v3
      with:
        push: true
        file: ${{ inputs.docker-file-path }}
        secrets: ENV_SECRETS=${{ inputs.env-secrets-b64 }}
        tags: |
          ${{ inputs.image-name }}:${{ inputs.image-tag }}