name: Update Docker Images
description: Update docker images in GCP Artifact Registry
inputs:
  docker-registry-name:
    required: true
    description: GCP Docker Registry name
  pytorch-image-name-dev:
    required: true
    description: PyTorch Image name in the artifact registry for prod environment
  pytorch-image-name-prod:
    required: true
    description: PyTorch Image name in the artifact registry for dev environment
  pytorch-cuda-image-name-dev:
    required: true
    description: PyTorch CUDA Image name in the artifact registry for dev environment
  pytorch-cuda-image-name-prod:
    required: true
    description: PyTorch CUDA Image name in the artifact registry for prod environment
  gcp-provider-id:
    required: true
    description: CAS GCP Provider ID
  gcp-service-account-email:
    required: true
    description: CAS Deployer Service Account email
  image-tag:
    required: true
    description: Current workflow tag
  env-secrets-b64:
    required: true
    description: Secret Environment variables (db hosts, password salt, etc)

runs:
  using: "composite"
  steps:
    - id: checkout
      name: Checkout
      uses: actions/checkout@v2

    - name: Authenticate with Google Cloud
      id: google-login
      uses: google-github-actions/auth@v0
      with:
        token_format: access_token
        workload_identity_provider: ${{ inputs.gcp-provider-id }}
        service_account: ${{ inputs.gcp-service-account-email }}
        access_token_lifetime: 1500s

    - name: Determine environment based on current tag
      id: get_environment
      run: |
        current_tag=$(echo "${{ github.ref }}" | awk -F'/' '{print $NF}')

        if [[ $current_tag == *"rc"* || $current_tag == *"a"* || $current_tag == *"b"* ]]; then
          echo "::set-output name=environment::development"
        else
          echo "::set-output name=environment::production"
        fi
      shell: bash

    - name: Login to Artifact Registry
      id: docker-google-login
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.docker-registry-name }}
        username: oauth2accesstoken
        password: ${{ steps.google-login.outputs.access_token }}

    - name: Debug current branch
      run: echo "Current branch is ${{ inputs.branch}}"
      shell: bash

    - name: Update CAS PyTorch image in Google Artifact Registry
      id: docker-push-pytorch-dev
      if: steps.get_environment.outputs.environment == 'development'
      uses: docker/build-push-action@v3
      with:
        push: true
        file: ./src/casp/services/deploy/Dockerfile.pytorch
        secrets: ENV_SECRETS=${{ inputs.env-secrets-b64 }}
        tags: |
          ${{ inputs.pytorch-image-name-dev }}:${{ inputs.image-tag }}
          ${{ inputs.pytorch-image-name-dev }}:latest

    - name: Update CAS PyTorch image in Google Artifact Registry
      id: docker-push-pytorch-prod
      if: steps.get_environment.outputs.environment == 'production'
      uses: docker/build-push-action@v3
      with:
        push: true
        file: ./src/casp/services/deploy/Dockerfile.pytorch
        secrets: ENV_SECRETS=${{ inputs.env-secrets-b64 }}
        tags: |
          ${{ inputs.pytorch-image-name-prod }}:${{ inputs.image-tag }}
          ${{ inputs.pytorch-image-name-prod }}:latest

    - name: Update CAS PyTorch CUDA image in Google Artifact Registry
      id: docker-push-pytorch-cuda-dev
      if: steps.get_environment.outputs.environment == 'development'
      uses: docker/build-push-action@v3
      with:
        push: true
        file: ./src/casp/services/deploy/Dockerfile.pytorch_cuda
        secrets: ENV_SECRETS=${{ inputs.env-secrets-b64 }}
        tags: |
          ${{ inputs.pytorch-cuda-image-name-dev }}:${{ inputs.image-tag }}
          ${{ inputs.pytorch-cuda-image-name-dev }}:latest

    - name: Update CAS PyTorch CUDA image in Google Artifact Registry
      id: docker-push-pytorch-cuda-prod
      if: steps.get_environment.outputs.environment == 'production'
      uses: docker/build-push-action@v3
      with:
        push: true
        file: ./src/casp/services/deploy/Dockerfile.pytorch_cuda
        secrets: ENV_SECRETS=${{ inputs.env-secrets-b64 }}
        tags: |
          ${{ inputs.pytorch-cuda-image-name-prod }}:${{ inputs.image-tag }}
          ${{ inputs.pytorch-cuda-image-name-prod }}:latest
