name: Update Docker Images
description: Update docker images in GCP Artifact Registry
inputs:
  docker-registry-name:
    required: true
    description: GCP Docker Registry name
  pytorch-image-name:
    required: true
    description: CAS Pytorch Image name in the artifact registry
  pytorch-cuda-image-name:
    required: true
    description: CAS Pytorch CUDA Image name in the artifact registry
  gcp-provider-id:
    required: true
    description: CAS GCP Provider ID
  gcp-service-account-email:
    required: true
    description: CAS Deployer Service Account email
  image-tag:
    required: true
    description: Current workflow tag
  env-b64:
    required: true
    description: CAS services env variable

runs:
  using: "composite"
  steps:
    - id: checkout
      name: Checkout
      uses: actions/checkout@v2

    - name: Add Application Environment Variables to .env
      run: |
        echo ${{ inputs.env-b64 }}
        echo ${{ inputs.env-b64 }} | base64 -d >> src/casp/.env
        echo $(ls -f src/casp/)
      shell: bash

    - name: Authenticate with Google Cloud
      id: google-login
      uses: google-github-actions/auth@v0
      with:
        token_format: access_token
        workload_identity_provider: ${{ inputs.gcp-provider-id }}
        service_account: ${{ inputs.gcp-service-account-email }}
        access_token_lifetime: 900s

    - name: Login to Artifact Registry
      id: docker-google-login
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.docker-registry-name }}
        username: oauth2accesstoken
        password: ${{ steps.google-login.outputs.access_token }}

    - name: Update CAS Pytorch image in Google Artifact Registry
      id: docker-push-pytorch-tagged
      uses: docker/build-push-action@v2
      with:
        push: true
        file: ./src/casp/services/deploy/Dockerfile.pytorch
        tags: |
          ${{ inputs.pytorch-image-name }}:${{ inputs.image-tag }}

    - name: Update CAS Pytorch CUDA image in Google Artifact Registry
      id: docker-push-pytorch-cuda-tagged
      uses: docker/build-push-action@v2
      with:
        push: true
        file: ./src/casp/services/deploy/Dockerfile.pytorch_cuda
        tags: |
          ${{ inputs.pytorch-cuda-image-name }}:${{ inputs.image-tag }}