"""0009_remove_bq_temp_table_from_model_add_bq_dataset

Revision ID: 9987ce21c5f8
Revises: 0008
Create Date: 2023-12-04 08:40:32.734412

"""

import sqlalchemy as sa
from alembic import op

from casp.services import settings

# revision identifiers, used by Alembic.
revision = "0009"
down_revision = "0008"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column("cas_model", sa.Column("bq_dataset_name", sa.String(length=255), nullable=True))
    op.execute(f"UPDATE cas_model SET bq_dataset_name = '{settings.DEFAULT_MODEL_BQ_DATASET_NAME}';")
    op.alter_column("cas_model", "bq_dataset_name", nullable=False)
    op.drop_column("cas_model", "bq_temp_table_dataset")
    op.drop_column("cas_model", "bq_cell_info_table_fqn")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cas_model", sa.Column("bq_cell_info_table_fqn", sa.VARCHAR(length=255), autoincrement=False, nullable=False)
    )
    op.add_column(
        "cas_model", sa.Column("bq_temp_table_dataset", sa.VARCHAR(length=255), autoincrement=False, nullable=False)
    )
    op.alter_column("cas_model", "model_name", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.drop_column("cas_model", "bq_dataset_name")
    op.alter_column("cas_matching_engine_index", "index_name", existing_type=sa.VARCHAR(length=255), nullable=True)
    # ### end Alembic commands ###
