"""Rename column system_name

Revision ID: 255e2d2a6030
Revises: 96d87d8dd7ad
Create Date: 2023-09-12 17:17:16.219869

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "255e2d2a6030"
down_revision = "96d87d8dd7ad"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cas_matching_engine_index", sa.Column("index_name", sa.String(length=255), nullable=True))
    op.drop_constraint("cas_matching_engine_index_system_name_key", "cas_matching_engine_index", type_="unique")
    op.create_unique_constraint(None, "cas_matching_engine_index", ["index_name"])
    op.drop_column("cas_matching_engine_index", "system_name")
    op.add_column("cas_model", sa.Column("model_name", sa.String(length=255), nullable=True))
    op.drop_constraint("cas_model_system_name_key", "cas_model", type_="unique")
    op.create_unique_constraint(None, "cas_model", ["model_name"])
    op.drop_column("cas_model", "system_name")
    # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('cas_model', sa.Column('system_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
#     op.drop_constraint(None, 'cas_model', type_='unique')
#     op.create_unique_constraint('cas_model_system_name_key', 'cas_model', ['system_name'])
#     op.drop_column('cas_model', 'model_name')
#     op.add_column('cas_matching_engine_index', sa.Column('system_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
#     op.drop_constraint(None, 'cas_matching_engine_index', type_='unique')
#     op.create_unique_constraint('cas_matching_engine_index_system_name_key', 'cas_matching_engine_index', ['system_name'])
#     op.drop_column('cas_matching_engine_index', 'index_name')
#     # ### end Alembic commands ###
