"""Update Matching Engine

Revision ID: 3518a8f30bcd
Revises: ec51111f100f
Create Date: 2023-05-11 14:32:46.029992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3518a8f30bcd'
down_revision = 'ec51111f100f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cas_matching_engine_index', sa.Column('endpoint_id', sa.String(length=255), nullable=False))
    op.add_column('cas_matching_engine_index', sa.Column('deployed_index_id', sa.String(length=255), nullable=False))
    op.drop_constraint('cas_matching_engine_index_matching_engine_endpoint_key', 'cas_matching_engine_index', type_='unique')
    op.drop_constraint('cas_matching_engine_index_matching_engine_index_name_key', 'cas_matching_engine_index', type_='unique')
    op.create_unique_constraint(None, 'cas_matching_engine_index', ['deployed_index_id'])
    op.create_unique_constraint(None, 'cas_matching_engine_index', ['endpoint_id'])
    op.drop_column('cas_matching_engine_index', 'matching_engine_index_name')
    op.drop_column('cas_matching_engine_index', 'matching_engine_endpoint')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cas_matching_engine_index', sa.Column('matching_engine_endpoint', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('cas_matching_engine_index', sa.Column('matching_engine_index_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cas_matching_engine_index', type_='unique')
    op.drop_constraint(None, 'cas_matching_engine_index', type_='unique')
    op.create_unique_constraint('cas_matching_engine_index_matching_engine_index_name_key', 'cas_matching_engine_index', ['matching_engine_index_name'])
    op.create_unique_constraint('cas_matching_engine_index_matching_engine_endpoint_key', 'cas_matching_engine_index', ['matching_engine_endpoint'])
    op.drop_column('cas_matching_engine_index', 'deployed_index_id')
    op.drop_column('cas_matching_engine_index', 'endpoint_id')
    # ### end Alembic commands ###
