"""Create CASModel and CASMatchingEngine db tables

Revision ID: 3c82590e357f
Revises: 62cf59b07367
Create Date: 2023-04-06 16:45:40.050444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c82590e357f'
down_revision = '62cf59b07367'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cas_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_name', sa.String(length=255), nullable=False),
    sa.Column('model_file_path', sa.String(length=255), nullable=False),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False),
    sa.Column('admin_use_only', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_file_path'),
    sa.UniqueConstraint('system_name')
    )
    op.create_table('cas_matching_engine_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_name', sa.String(length=255), nullable=False),
    sa.Column('matching_engine_index_name', sa.String(length=255), nullable=False),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False),
    sa.Column('model_endpoint_url', sa.String(length=255), nullable=True),
    sa.Column('matching_engine_endpoint', sa.String(length=255), nullable=True),
    sa.Column('admin_use_only', sa.Boolean(), nullable=False),
    sa.Column('cas_model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cas_model_id'], ['cas_model.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matching_engine_endpoint'),
    sa.UniqueConstraint('matching_engine_index_name'),
    sa.UniqueConstraint('model_endpoint_url'),
    sa.UniqueConstraint('system_name')
    )
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    op.drop_table('cas_matching_engine_index')
    op.drop_table('cas_model')
    # ### end Alembic commands ###
