"""Initial Migration: User model

Revision ID: 609b6749b472
Revises:
Create Date: 2023-01-18 15:36:42.358885

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "609b6749b472"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("cas_request_count", sa.Integer(), nullable=False),
        sa.Column("cas_scRNA_cells_processed", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
