"""Model Index Endpoint ID unique to False

Revision ID: 96d87d8dd7ad
Revises: 37fbe8997eca
Create Date: 2023-08-03 13:48:22.744381

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "96d87d8dd7ad"
down_revision = "37fbe8997eca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("cas_matching_engine_index_endpoint_id_key", "cas_matching_engine_index", type_="unique")
    # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_unique_constraint(
#         "cas_matching_engine_index_endpoint_id_key", "cas_matching_engine_index", ["endpoint_id"]
#     )
#     # ### end Alembic commands ###
