"""Matching Engine and Model

Revision ID: ec51111f100f
Revises: 62cf59b07367
Create Date: 2023-05-11 14:27:19.300971

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ec51111f100f"
down_revision = "62cf59b07367"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cas_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("system_name", sa.String(length=255), nullable=False),
        sa.Column("model_file_path", sa.String(length=255), nullable=False),
        sa.Column("embedding_dimension", sa.Integer(), nullable=False),
        sa.Column("admin_use_only", sa.Boolean(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_file_path"),
        sa.UniqueConstraint("system_name"),
    )
    op.create_table(
        "cas_matching_engine_index",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("system_name", sa.String(length=255), nullable=False),
        sa.Column("matching_engine_index_name", sa.String(length=255), nullable=False),
        sa.Column("embedding_dimension", sa.Integer(), nullable=False),
        sa.Column("matching_engine_endpoint", sa.String(length=255), nullable=True),
        sa.Column("admin_use_only", sa.Boolean(), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["cas_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("matching_engine_endpoint"),
        sa.UniqueConstraint("matching_engine_index_name"),
        sa.UniqueConstraint("system_name"),
    )
    op.add_column("user", sa.Column("is_admin", sa.Boolean(), nullable=True))
    op.execute("UPDATE user SET is_admin = false")
    op.alter_column("cas_model", "is_default_model", nullable=False)
    # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_column("user", "is_admin")
#     op.drop_table("cas_matching_engine_index")
#     op.drop_table("cas_model")
#     # ### end Alembic commands ###
