"""Add is_represntation to CASModel

Revision ID: 38dfb0da8f6a
Revises: cdfe110d1068
Create Date: 2025-10-02 17:34:52.102519

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "38dfb0da8f6a"
down_revision = "cdfe110d1068"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Set a new column nullable, fill in default values, make it non nullable
    op.add_column("ml_management_model", sa.Column("is_representation_model", sa.Boolean(), nullable=True))
    op.execute(f"update ml_management_model set is_representation_model = true;")
    op.alter_column("ml_management_model", "is_representation_model", existing_type=sa.Boolean(), nullable=False)
    # Update embedding_dimension requirement.
    op.alter_column("ml_management_model", "embedding_dimension", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("ml_management_model", "embedding_dimension", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("ml_management_model", "is_representation_model")
    # ### end Alembic commands ###
