pca_embed_and_index_create_pipeline:
  machine_specs:
    pca_embed:
      display_name: PCA Embed
      replica_count: 1
      machine_type: n1-highmem-16
      accelerator_type: NVIDIA_TESLA_T4
      accelerator_count: 1
      base_image: us-central1-docker.pkg.dev/dsp-cell-annotation-service/cas-services-cicd/cas-pytorch-cuda-pipeline-dev:1.4.6-alpha.1
      service_account: backend-service-account@dsp-cell-annotation-service.iam.gserviceaccount.com
      env:
        - name: WANDB_API_KEY
          value: 2bc373264f98a15fac0e869d98f7b207d575937d
        - name: PROJECT_BUCKET_NAME
          value: cellarium-file-system
        - name: LOG_AS_JSON
          value: "false"
        - name: SENTRY_DSN
          value: dummysecret
        - name: SENTRY_ENVIRONMENT
          value: dummyenvironment
        - name: NEPTUNE_API_KEY
          value: notusinganymore
        - name: DB_CONNECTION_NAME
          value: notusingnow
        - name: DB_NAME
          value: dummyname
        - name: DB_PASSWORD
          value: dummypass
        - name: DB_USER
          value: dummyuser
        - name: DB_INSTANCE_UNIX_SOCKET
          value: dummysocket
        - name: DB_PORT
          value: "2000"
        - name: DB_PRIVATE_IP
          value: privatewhat
        - name: SECRET_KEY
          value: dummysecretistilllsecret
        - name: SECURITY_PASSWORD_SALT
          value: verysecurysalt
        - name: FLASK_BASIC_AUTH_USERNAME
          value: dummyusername
        - name: FLASK_BASIC_AUTH_PASSWORD
          value: dummyusername
        - name: ENVIRONMENT
          value: development

    pca_index_create:
      display_name: Index Create
      replica_count: 1
      accelerator_type: null
      accelerator_count: 1
      machine_type: n1-standard-4
      base_image: us-central1-docker.pkg.dev/dsp-cell-annotation-service/cas-services-cicd/cas-pytorch-pipeline-dev:1.4.6-alpha.1
      service_account: backend-service-account@dsp-cell-annotation-service.iam.gserviceaccount.com
      env:
        - name: WANDB_API_KEY
          value: 2bc373264f98a15fac0e869d98f7b207d575937d
        - name: PROJECT_BUCKET_NAME
          value: cellarium-file-system
        - name: LOG_AS_JSON
          value: "false"
        - name: SENTRY_DSN
          value: dummysecret
        - name: SENTRY_ENVIRONMENT
          value: dummyenvironment
        - name: NEPTUNE_API_KEY
          value: notusinganymore
        - name: DB_CONNECTION_NAME
          value: notusingnow
        - name: DB_NAME
          value: dummyname
        - name: DB_PASSWORD
          value: dummypass
        - name: DB_USER
          value: dummyuser
        - name: DB_INSTANCE_UNIX_SOCKET
          value: dummysocket
        - name: DB_PORT
          value: "2000"
        - name: DB_PRIVATE_IP
          value: privatewhat
        - name: SECRET_KEY
          value: dummysecretistilllsecret
        - name: SECURITY_PASSWORD_SALT
          value: verysecurysalt
        - name: FLASK_BASIC_AUTH_USERNAME
          value: dummyusername
        - name: FLASK_BASIC_AUTH_PASSWORD
          value: dummyusername
        - name: ENVIRONMENT
          value: development

  pipeline_configs:
    - curriculum_name: cellarium_mouse_pca_v11beta_drf_gt_3_20241126
      model_name: pca_64_defaultcutoffs_log1p_zscore
      schema_name: refdata-gex-mm10-2020-A
      embedding_dimension: 64
      shard_size: 10000
      extract_start: 0
      extract_end: 376
      last_shard_size: 3231
      use_log_1p: true
      use_z_score: true
      use_divide_by_scale: false
      use_filter: true
      mean_var_std_model_name: mean_var_std_log1p
      tdigest_model_name: tdigest_log1p
      filter_file_name: mean-var-std-highly-variable-genes-log1p-default-cutoffs.csv
      normalize_total_target_count: 10000
      normalize_total_eps: 1e-6
      pca_embed__n_components: 64
      use_wandb: false
      pca_index_create__index_location: us-central1
      pca_index_create__index_endpoint_id: projects/350868384795/locations/us-central1/indexEndpoints/2348891088464379904
      feature_norm_type: UNIT_L2_NORM
      display_name: pca_mouse_64_defaultcutoffs_log1p_zscore_index
      distance_measure_type: DOT_PRODUCT_DISTANCE
      leaf_node_embedding_count: 1000
      approximate_neighbors_count: 512

