FROM bitnami/pytorch:latest
WORKDIR /app
USER root

# Copy Files and Secrets
COPY requirements.txt .
COPY src .
RUN --mount=type=secret,id=_env,dst=/etc/secrets/.env cat /etc/secrets/.env >> ./casp/.env

# Install Dependencies
RUN pip install -r requirements.txt

# Create a dockeruser to own the app
RUN useradd -r dockeruser
RUN chown dockeruser: /app
USER dockeruser

EXPOSE 8000
ENV PYTHONPATH "${PYTHONPATH}:/app"