"""0008_add_approximate_number_of_neighbors

Revision ID: 2f70ad2c4fa3
Revises: 255e2d2a6030
Create Date: 2023-11-07 14:55:10.188743

"""

import sqlalchemy as sa
from alembic import op

from casp.services import settings

# revision identifiers, used by Alembic.
revision = "0008"
down_revision = "255e2d2a6030"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cas_matching_engine_index", sa.Column("num_neighbors", sa.Integer(), nullable=True))
    op.execute(f"UPDATE cas_matching_engine_index SET num_neighbors = {settings.KNN_SEARCH_NUM_MATCHES_DEFAULT}")
    op.alter_column("cas_matching_engine_index", "num_neighbors", nullable=False)
    # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column("cas_model", "model_name", existing_type=sa.VARCHAR(length=255), nullable=True)
#     op.alter_column("cas_matching_engine_index", "index_name", existing_type=sa.VARCHAR(length=255), nullable=True)
#     op.drop_column("cas_matching_engine_index", "num_neighbors")
#     # ### end Alembic commands ###
