"""Cas Model is_default

Revision ID: 37fbe8997eca
Revises: 75ad185b37c1
Create Date: 2023-06-26 13:06:00.423698

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "37fbe8997eca"
down_revision = "75ad185b37c1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cas_model", sa.Column("is_default_model", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE cas_model SET is_default_model = false")
    op.alter_column("cas_model", "is_default_model", nullable=False)


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_column("cas_model", "is_default_model")
#     # ### end Alembic commands ###
