# Created from uvicorn's default log_config which is defined in uvicorn.config.LOGGING_CONFIG
version: 1
disable_existing_loggers: false
formatters:
  default:
    (): casp.services.logging.CustomDefaultFormatter
    fmt: '%(levelprefix)s %(message)s'
    fmt_json: '%(message)s'
    use_colors: null
  access:
    (): casp.services.logging.CustomAccessFormatter
    fmt: '%(levelprefix)s %(client_addr)s "%(user)s" "%(request_line)s" %(user_agent)s %(status_code)s'
    fmt_json: '%(client_addr)s "%(user)s" "%(request_line)s" %(user_agent)s %(status_code)s'
handlers:
  default:
    formatter: default
    class: casp.services.logging.StreamHandler
    stream: 'ext://sys.stderr'
  access:
    formatter: access
    class: casp.services.logging.StreamHandler
    stream: 'ext://sys.stdout'
loggers:
  root:
    handlers:
      - default
    level: INFO
    propagate: false
  uvicorn:
    handlers:
      - default
    level: INFO
    propagate: false
  uvicorn.error:
    level: INFO
  uvicorn.access:
    handlers:
      - access
    level: INFO
    propagate: false
