FROM anibali/pytorch:1.8.1-cuda11.1

USER root
RUN groupadd -r dockuser && useradd -r -g dockuser dockuser
WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY src .

ENV PYTHONPATH "${PYTHONPATH}:/app"