calculate_metrics:
  machine_specs:
    calculate_metrics:
      display_name: Calculate Metrics
      replica_count: 1
      machine_type: e2-standard-32
      accelerator_type: null
      accelerator_count: null
      base_image: us-central1-docker.pkg.dev/dsp-cell-annotation-service/cas-services-cicd/cas-pytorch-pipeline-dev:1.4.6-alpha.1
      env:
        - name: WANDB_API_KEY
          value: 2bc373264f98a15fac0e869d98f7b207d575937d
      packages_to_install:
        - git+https://github.com/cellarium-ai/cellarium-cas.git@1.4.11+benchmarking.1
        - owlready2

  pipeline_configs:
    - batch_size: 10000
      calculate_metrics__model_name: pca_256_fullschema
      cas_result_paths: gs://cellarium-file-system/dev/benchmarking_june_2024/metadata/cas_outputs_mouse/pca_256_fullschema_cas_outputs.txt
      cell_ontology_resource_path: gs://cellarium-file-system/dev/benchmarking_june_2024/metadata/benchmarking_resource_schema_5-0.pickle
      dataset_paths: gs://cellarium-file-system/dev/benchmarking_june_2024/metadata/dataset_paths_mouse.txt
      metrics_metadata_path: gs://cellarium-file-system/dev/benchmarking_june_2024/metrics_mouse
      num_hops: 4
      wandb_project: bench_mouse
    - batch_size: 10000
      calculate_metrics__model_name: pca_64_fullschema
      cas_result_paths: gs://cellarium-file-system/dev/benchmarking_june_2024/metadata/cas_outputs_mouse/pca_64_fullschema_cas_outputs.txt
      cell_ontology_resource_path: gs://cellarium-file-system/dev/benchmarking_june_2024/metadata/benchmarking_resource_schema_5-0.pickle
      dataset_paths: gs://cellarium-file-system/dev/benchmarking_june_2024/metadata/dataset_paths_mouse.txt
      metrics_metadata_path: gs://cellarium-file-system/dev/benchmarking_june_2024/metrics_mouse
      num_hops: 4
      wandb_project: bench_mouse
    - batch_size: 10000
      calculate_metrics__model_name: pca_64_hv10000_log1p_zscore
      cas_result_paths: gs://cellarium-file-system/dev/benchmarking_june_2024/metadata/cas_outputs_mouse/pca_64_hv10000_log1p_zscore_cas_outputs.txt
      cell_ontology_resource_path: gs://cellarium-file-system/dev/benchmarking_june_2024/metadata/benchmarking_resource_schema_5-0.pickle
      dataset_paths: gs://cellarium-file-system/dev/benchmarking_june_2024/metadata/dataset_paths_mouse.txt
      metrics_metadata_path: gs://cellarium-file-system/dev/benchmarking_june_2024/metrics_mouse
      num_hops: 4
      wandb_project: bench_mouse
    - batch_size: 10000
      calculate_metrics__model_name: pca_256_fullschema_log1p_zscore
      cas_result_paths: gs://cellarium-file-system/dev/benchmarking_june_2024/metadata/cas_outputs_mouse/pca_256_fullschema_log1p_zscore_cas_outputs.txt
      cell_ontology_resource_path: gs://cellarium-file-system/dev/benchmarking_june_2024/metadata/benchmarking_resource_schema_5-0.pickle
      dataset_paths: gs://cellarium-file-system/dev/benchmarking_june_2024/metadata/dataset_paths_mouse.txt
      metrics_metadata_path: gs://cellarium-file-system/dev/benchmarking_june_2024/metrics_mouse
      num_hops: 4
      wandb_project: bench_mouse
    - batch_size: 10000
      calculate_metrics__model_name: pca_256_fullschema_log1p
      cas_result_paths: gs://cellarium-file-system/dev/benchmarking_june_2024/metadata/cas_outputs_mouse/pca_256_fullschema_log1p_cas_outputs.txt
      cell_ontology_resource_path: gs://cellarium-file-system/dev/benchmarking_june_2024/metadata/benchmarking_resource_schema_5-0.pickle
      dataset_paths: gs://cellarium-file-system/dev/benchmarking_june_2024/metadata/dataset_paths_mouse.txt
      metrics_metadata_path: gs://cellarium-file-system/dev/benchmarking_june_2024/metrics_mouse
      num_hops: 4
      wandb_project: bench_mouse