generate_cas_outputs_pipeline:
  machine_specs:
    generate_cas_outputs:
      pca_resize_and_save:
      display_name: Resize PCA Model and Save
      replica_count: 1
      accelerator_type: null
      accelerator_count: 1
      machine_type: n1-highmem-16
      base_image: us-central1-docker.pkg.dev/dsp-cell-annotation-service/cas-services-cicd/cas-pytorch-pipeline-dev:1.4.6-alpha.1
      service_account: backend-service-account@dsp-cell-annotation-service.iam.gserviceaccount.com
      packages_to_install:
        - git+https://github.com/cellarium-ai/cellarium-cas.git@1.5.2
        - owlready2


  pipeline_configs:
    - cas_api_token: 521da69c-6977-4913-a32b-b1ded563f170.e07f59d5-7043-4a8c-84b0-17d09f076ca2
      cas_api_url: https://benchmarking-cas-api-vi7nxpvk7a-uc.a.run.app
      cas_results_output_path: gs://cellarium-file-system/dev/benchmarking_june_2024/cas_outputs_model_dfr_gt_3
      dataset_paths: gs://cellarium-file-system/dev/benchmarking_june_2024/metadata/dataset_paths.txt
      deployed_index_id: deployed_pca_ebd_dfrgt3_64_hvcutoffsgenes_log1p_zscore_index
      generate_cas_outputs__model_name: pca_ebd_dfrgt3_64_hvcutoffsgenes_log1p_zscore
      index_display_name: pca_ebd_dfrgt3_64_hvcutoffsgenes_log1p_zscore_index
      index_endpoint_id: 2348891088464379904
      index_id: 2392726418040553472
      index_name: pca_ebd_dfrgt3_64_hvcutoffsgenes_log1p_zscore_index
      index_region: us-central1
      project_id: dsp-cell-annotation-service