gcs_bucket_name: ${gcs_bucket_name}
gcs_file_path: ${gcs_file_path}
uns_meta_keys: ${uns_meta_keys}
cas_cell_index_start: ${cas_cell_index_start}
cas_feature_index_start: ${cas_feature_index_start}
load_uns_data: ${load_uns_data}
original_feature_id_lookup: ${original_feature_id_lookup}
dataset_id: ${dataset_id}
dataset_version_id: ${dataset_version_id}
gcs_stage_dir: ${gcs_stage_dir}