wandb_project: ${wandb_project}
dataset_paths: ${dataset_paths}
model_name: ${model_name}
cell_ontology_resource_path: ${cell_ontology_resource_path}
cl_labels_to_names_map_path: ${cl_labels_to_names_map_path}
metrics_metadata_path: ${metrics_metadata_path}
cas_result_paths: ${cas_result_paths}
num_hops: ${num_hops}
batch_size: ${batch_size}