model_name: ${model_name}
display_name: ${display_name}
index_endpoint_id: ${index_endpoint_id}
location: ${index_location}
embedding_dimension: ${embedding_dimension}
contents_delta_uri: ${contents_delta_uri}
approximate_neighbors_count: ${approximate_neighbors_count}
distance_measure_type: ${distance_measure_type}
feature_norm_type: ${feature_norm_type}
leaf_node_embedding_count: ${leaf_node_embedding_count}