name: Run cellarium-cas integration tests
description: Runs the integration tests from the cellarium-cas repository
inputs:
  revision:
    description: The revision of the cellarium-cas repository to use
    required: false
    default: main
  api-key:
    description: The API key for connecting to the CAS API
    required: true
  api-url:
    description: The URL of the CAS API service
    required: true

runs:
  using: "composite"
  steps:
    - id: checkout
      name: Checkout
      uses: actions/checkout@v4
      with:
        repository: "cellarium-ai/cellarium-cas"
        ref: ${{ inputs.revision }}
        path: "./cellarium-cas"
    
    - id: install-dependencies
      name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.txt
      shell: bash
      working-directory: ./cellarium-cas
    
    - id: run-tests
      name: Run tests
      env:
        TEST_API_TOKEN: ${{ inputs.api-key }}
        TEST_API_URL: ${{ inputs.api-url }}
        CAS_VERSION: "1.4.5"
      run: |
        tox -e integration 
      shell: bash
      working-directory: ./cellarium-cas