name: CAS Repository Docker Build Workflow
on:
  workflow_dispatch:
    inputs:
      service-type:
        description: 'Service type to build. Can be `compute`, `admin` or `both`. Default is `both`.'
        required: false
        default: 'both'
        type: choice
        options:
          - both
          - compute
          - admin
      image-tag:
        description: 'Docker image tag. Will use the short hash of the last commit in the branch if nothing is passed in.'
        required: false
        default: ''
      add-latest-tag:
        description: 'Push a `latest` tag to the artifact registry. Default is `true`.'
        required: false
        default: true
        type: boolean

jobs:

  update-docker-images:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    strategy:
      matrix:
        service-type: [ 'compute', 'admin' ]

    env:
      DOCKER_REGISTRY_NAME: us-central1-docker.pkg.dev
      COMPUTE_IMAGE_NAME: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cas-services-cicd/cas-compute
      ADMIN_IMAGE_NAME: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cas-services-cicd/cas-admin
    steps:
      - uses: actions/checkout@v4

      - id: get-image-tag
        name: Get tag
        run: |
          if [[ "${{ inputs.image-tag }}" == "" ]]; then
            echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${{ inputs.image-tag }}" >> $GITHUB_ENV
          fi
        shell: bash
      - id: build-compute
        uses: ./.github/actions/docker-build
        if: matrix.service-type == 'compute' && (inputs.service-type == 'compute' || inputs.service-type == 'both')
        with:
          docker-registry-name: ${{ env.DOCKER_REGISTRY_NAME }}
          image-name: ${{ env.COMPUTE_IMAGE_NAME }}
          image-tag: ${{ env.IMAGE_TAG }}
          service-type: ${{ matrix.service-type }}
          gcp-provider-id: ${{ secrets.GCP_PROVIDER_ID }}
          gcp-service-account-email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          add-latest-tag: ${{ inputs.add-latest-tag }}

      - id: build-admin
        uses: ./.github/actions/docker-build
        if: matrix.service-type == 'admin' && (inputs.service-type == 'admin' || inputs.service-type == 'both')
        with:
          docker-registry-name: ${{ env.DOCKER_REGISTRY_NAME }}
          image-name: ${{ env.ADMIN_IMAGE_NAME }}
          image-tag: ${{ env.IMAGE_TAG }}
          service-type: ${{ matrix.service-type }}
          gcp-provider-id: ${{ secrets.GCP_PROVIDER_ID }}
          gcp-service-account-email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          add-latest-tag: ${{ inputs.add-latest-tag }}