name: CAS Repository Update Workflow
on: [push, workflow_dispatch]
jobs:
#  unit-tests:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        python-version: [ '3.10' ]
#    steps:
#      - uses: actions/checkout@v2
#      - uses: ./.github/actions/unit-tests
#        with:
#          python-version: ${{ matrix.python-version }}

  update-docker-images:
#    needs: [unit-tests]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    permissions:
      contents: write
      id-token: write

    env:
      DOCKER_REGISTRY_NAME: us-central1-docker.pkg.dev

    strategy:
      matrix:
        include:
          - name: PyTorch Docker
            docker-file-path: ./src/casp/services/deploy/Dockerfile.pytorch
            image-name: us-central1-docker.pkg.dev/dsp-cell-annotation-service/cas-services-cicd/cas-pytorch
          - name: PyTorch CUDA Docker
            docker-file-path: ./src/casp/services/deploy/Dockerfile.pytorch_cuda
            image-name: us-central1-docker.pkg.dev/dsp-cell-annotation-service/cas-services-cicd/cas-pytorch-cuda
          - name: PyTorch Pipeline
            docker-file-path: ./src/casp/services/deploy/Dockerfile.pytorch_pipeline
            image-name: us-central1-docker.pkg.dev/dsp-cell-annotation-service/cas-services-cicd/cas-pytorch-pipeline
          - name: PyTorch CUDA Pipeline
            docker-file-path: ./src/casp/services/deploy/Dockerfile.pytorch_cuda_pipeline
            image-name: us-central1-docker.pkg.dev/dsp-cell-annotation-service/cas-services-cicd/cas-pytorch-cuda-pipeline

    # Notice: this job runs only on tagged commit:
    steps:
      - uses: actions/checkout@v2
      - id: get-tag
        name: Get tag
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: ./.github/actions/docker-update
        with:
          docker-registry-name: ${{ env.DOCKER_REGISTRY_NAME }}
          image-tag: ${{ env.TAG }}
          gcp-provider-id: ${{ secrets.GCP_PROVIDER_ID }}
          gcp-service-account-email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          env-secrets-b64: ${{ secrets.CAS_SERVICES_ENV_b64 }}
          image-name: ${{ matrix.image-name }}
          docker-file-path: ${{ matrix.docker-file-path }}
